# то что хранится в объекте message

{'content_type': 'text',
 'message_id': 231,
 'from_user': {'id': 222443632, 'is_bot': False,
               'first_name': 'Aleksey', 'username': None,
               'last_name': 'Frundin', 'language_code': 'en'},
 'date': 1512566341,
 'chat': {'type': 'private',
          'last_name': 'Frundin',
          'first_name': 'Aleksey',
          'username': None,
          'id': 222443632,
          'title': None,
          'all_members_are_administrators': None,
          'photo': None,
          'description': None,
          'invite_link': None,
          'pinned_message': None,
          'sticker_set_name': None,
          'can_set_sticker_set': None},
 'forward_from_chat': None,
 'forward_from': None,
 'forward_date': None,
 'reply_to_message': None,
 'edit_date': None,
 'author_signature': None,
 'text': '18',
 'entities': None,
 'caption_entities': None,
 'audio': None,
 'document': None,
 'photo': None,
 'sticker': None,
 'video': None,
 'video_note': None,
 'voice': None,
 'caption': None,
 'contact': None,
 'location': None,
 'venue': None,
 'new_chat_member': None,
 'new_chat_members': None,
 'left_chat_member': None,
 'new_chat_title': None,
 'new_chat_photo': None,
 'delete_chat_photo': None,
 'group_chat_created': None,
 'supergroup_chat_created': None,
 'channel_chat_created': None,
 'migrate_to_chat_id': None,
 'migrate_from_chat_id': None,
 'pinned_message': None,
 'invoice': None,
 'successful_payment': None}
